version: '3.2'
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app/backend
    ports:
      - '4000:4000'
    stdin_open: true
    tty: true
    environment:
      - DB_HOST=db
      - DB_NAME=backend
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
    depends_on:
      - db
  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=backend
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword

